---
title: errors.proto
hide_title: true
---

import { ProtoMessage, ProtoServiceMethod, ProtoEnum } from '@theme/ProtoFile';

# `errors.proto`
_**path** agntcy/identity/core/v1alpha1/errors.proto_

_**package** agntcy.identity.core.v1alpha1_



---

## Messages


### `ErrorInfo`
<ProtoMessage key={0} message={{"name":"ErrorInfo","longName":"ErrorInfo","fullName":"agntcy.identity.core.v1alpha1.ErrorInfo","description":"Describes the cause of the error with structured details.","hasExtensions":false,"hasFields":true,"hasOneofs":true,"extensions":[],"fields":[{"name":"reason","description":"The reason of the error, as defined by the ErrorReason enum.\nThis is a constant unique value that helps identify the cause of\nthe error.","label":"optional","type":"ErrorReason","longType":"ErrorReason","fullType":"agntcy.identity.core.v1alpha1.ErrorReason","ismap":false,"isoneof":true,"oneofdecl":"_reason","defaultValue":"","typeLink":"/protodocs/agntcy/identity/core/v1alpha1/errors.proto#errorreason"},{"name":"message","description":"The message describing the error in a human-readable way. This\nfield gives additional details about the error.","label":"optional","type":"string","longType":"string","fullType":"string","ismap":false,"isoneof":true,"oneofdecl":"_message","defaultValue":""}]}} />

---
## Enums


### `ErrorReason`
<ProtoEnum key={0} enumb={{"name":"ErrorReason","longName":"ErrorReason","fullName":"agntcy.identity.core.v1alpha1.ErrorReason","description":"Represents the reason for an error, providing a unique\nconstant value for the error.","values":[{"name":"ERROR_REASON_UNSPECIFIED","number":"0","description":"ERROR_REASON_UNSPECIFIED indicates that no specific error reason\nhas been specified."},{"name":"ERROR_REASON_INTERNAL","number":"1","description":"An internal error, this happens in case of unexpected condition or failure within the service"},{"name":"ERROR_REASON_INVALID_CREDENTIAL_ENVELOPE_TYPE","number":"2","description":"The credential envelope type is invalid. For valid values refer to\nthe enum CredentialEnvelopeType."},{"name":"ERROR_REASON_INVALID_CREDENTIAL_ENVELOPE_VALUE_FORMAT","number":"3","description":"The credential envelope value format does not correspond to the format\nspecified in envelope_type."},{"name":"ERROR_REASON_INVALID_ISSUER","number":"4","description":"The issuer contains one or more invalid fields."},{"name":"ERROR_REASON_ISSUER_NOT_REGISTERED","number":"5","description":"The issuer is not registered in the Node."},{"name":"ERROR_REASON_INVALID_VERIFIABLE_CREDENTIAL","number":"6","description":"The Verifiable Credential is invalid, this can be related to either\ninvalid format or unable to verify the Data Integrity proof."},{"name":"ERROR_REASON_IDP_REQUIRED","number":"7","description":"An issuer is required to have an external IdP"},{"name":"ERROR_REASON_INVALID_PROOF","number":"8","description":"The proof is invalid"},{"name":"ERROR_REASON_UNSUPPORTED_PROOF","number":"9","description":"The proof type is not supported"},{"name":"ERROR_REASON_RESOLVER_METADATA_NOT_FOUND","number":"10","description":"Unable to resolve an ID to a ResolverMetadata"},{"name":"ERROR_REASON_UNKNOWN_IDP","number":"11","description":"Unknown Identity Provider"},{"name":"ERROR_REASON_ID_ALREADY_REGISTERED","number":"12","description":"The ID and Resolver Metadata are already registered in the system"}]}} />

---


  